// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-2IjljB59DWt4nP2CQwkilWhNO0qb5v4',
    appId: '1:954629909845:web:1c4d094b59256e04ad53dc',
    messagingSenderId: '954629909845',
    projectId: 'rahtk-ecommerce-app',
    authDomain: 'rahtk-ecommerce-app.firebaseapp.com',
    storageBucket: 'rahtk-ecommerce-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPgPESlBSRSCDACtmBX7s-qkppikHd-TM',
    appId: '1:954629909845:android:8fbdc8c3d2179c49ad53dc',
    messagingSenderId: '954629909845',
    projectId: 'rahtk-ecommerce-app',
    storageBucket: 'rahtk-ecommerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3fggDTVbLEdoWiRqU58xzBwAyxfCpHbE',
    appId: '1:954629909845:ios:ba18fd40524dc2caad53dc',
    messagingSenderId: '954629909845',
    projectId: 'rahtk-ecommerce-app',
    storageBucket: 'rahtk-ecommerce-app.appspot.com',
    iosBundleId: 'com.example.rahtkMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3fggDTVbLEdoWiRqU58xzBwAyxfCpHbE',
    appId: '1:954629909845:ios:ba18fd40524dc2caad53dc',
    messagingSenderId: '954629909845',
    projectId: 'rahtk-ecommerce-app',
    storageBucket: 'rahtk-ecommerce-app.appspot.com',
    iosBundleId: 'com.example.rahtkMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-2IjljB59DWt4nP2CQwkilWhNO0qb5v4',
    appId: '1:954629909845:web:f5005b94b6246fd4ad53dc',
    messagingSenderId: '954629909845',
    projectId: 'rahtk-ecommerce-app',
    authDomain: 'rahtk-ecommerce-app.firebaseapp.com',
    storageBucket: 'rahtk-ecommerce-app.appspot.com',
  );
}
